version: '3.7'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      CAP_HOST_MANAGEMENT: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      internal:
    deploy:
      mode: global
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      internal:
      traefik_endpoint:
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        traefik.enable: 'true'
        traefik.http.routers.portainer.tls: 'true'
        traefik.http.routers.portainer.tls.certresolver: letsenc
        traefik.http.routers.portainer.entrypoints: https
        traefik.http.routers.portainer.rule: Host(`portainer.${DOMAIN_NAME}`)
        traefik.http.routers.portainer.middlewares: add-security-headers
        traefik.http.services.portainer.loadbalancer.server.port: 9000

networks:
  internal:
    attachable: true
  traefik_endpoint:
    external: true

volumes:
  portainer_data:
